version: '3.1'
services:
  library-db:
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: wad2022
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres